### ISSUE TITLE
Feature request: Add text to image

### ISSUE THREAD

**Issue by brgrp** [sneas/img-comparison-slider#135]
Hi,

I'd like to request the ability to add text overlays on top of images. This would allow users to provide context or 
explanations for what's shown in each image, making the slider more user-friendly and informative. Here are some possible use cases:

* Add a brief description of objects in the first image, such as "a cat sitting on a couch"
* Highlight specific details in the second image, such as "cat is replaced by a dog with AI"

I believe this feature would enhance the user experience and provide more context for users. Let me know if you're interested in
implementing or if there are other features you think would be valuable. Thanks!

**Comment by sneas** [comment]
Hi, @brgrp,

I'm sorry for the delayed response. I'm not sure I got it correctly.

`img-comparison-slider` is quite flexible, and basically is limited by HTML, CSS and JS. For example you can use your custom html instead of images as I did in this example: https://img-comparison-slider.sneas.io/examples.html#before-and-after-labels

Also, I use the same approach to provide an elaborate example of the slider on the homepage: https://img-comparison-slider.sneas.io

You can find the code of the example from the homepage here https://github.com/sneas/img-comparison-slider/blob/master/packages/www/src/views/index.hbs#L5-L78

Does my answer help?

**Comment by brgrp** [comment]
Hey @sneas,
that's exactly what I was looking for! I somehow missed that part - my fault.
Thank you!
