### ISSUE TITLE
Custom handle not changing size appropriately and loading too big

### ISSUE THREAD

**Issue by joanacdias** [sneas/img-comparison-slider#19]
When adding a custom handle with the same code as in your documentation, the handle appears way too big and does change size appropriately. Why is this?

<img width="326" alt="Screenshot 2021-01-28 at 12 40 47" src="https://user-images.githubusercontent.com/38839490/106140088-32b1be80-6166-11eb-8196-771825673f3a.png">

**Comment by sneas** [comment]
Hi Joan, it's difficult to say by the screenshot but I'd check that:

* Handle `<img />` tag doesn't have `width: 100%` property set via CSS your custom CSS.
* The size problem might be caused by `clamp`. I'd try to use this simpler example first https://sneas.github.io/img-comparison-slider/#custom-handle and check if the problem is still there.

**Comment by joanacdias** [comment]
width: 100% worked, thank you!

**Comment by Joey-Ma** [comment]
width: 100% worked, thank you!
